services:
  db:
    image: "postgres"
    container_name: db
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "kfkepit"
    networks:
      - mynetwork

  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - "5555:5555"
    environment:
      DB_URL: "postgres://postgres:123456@db:5432/kfkepit"
      PORT: "4000"
      SESSION_SECRET: "Vas7uWHR0e8YO34SYMqjZ8WhjNCZV6"
      NODE_ENV: "production"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./public:/usr/share/nginx/html/public
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
